## Analisis Numérico Ciclo 01-2021
                        
### Integrantes de Grupo: 

##### Mario Andrés Cálix Sosa 00309119
##### Kevin Alexander Cea Patriz 00203919
##### Diego Ernesto Polanco Ortiz 00301417

# Algoritmo de Strassen para multiplicación de matrices cuadradas

## Introducción 

La multiplicación de dos matrices de tamaño $\,N \times N\,$ A y B resultante en una matriz $\,C=A \times B\,$ se calcula por medio de una formula

general notada:  $$ C = AB := (c_{(i,j)}) = \sum^n_{t=1}a_{(i,t)}b_{(t,j)} $$

## Algoritmo de Dividir y Conquistar:

Sean dos matrices A y B cuadradas y queremos calcular la matriz C como producto 

$ C = AB \,$ con $ A,B,C \in R^{2^{n} \times 2^{n}} $  

Tenemos entonces las matrices siguientes: $$ A = \begin{pmatrix} A_{1,1} & A_{1.2} \\ A_{1,2} & A_{2,2} \end{pmatrix} ,
\,\,B = \begin{pmatrix} A_{1,1} & B_{1.2} \\ B_{1,2} & B_{2,2} \end{pmatrix} , 
C = \begin{pmatrix} C_{1,1} & C_{1.2} \\ C_{1,2} & C_{2,2} \end{pmatrix} $$


De tal modo obtenemos entonces: 
$ C_{1,1} = A_{1,1}B_{1,1} \,\,+ A_{1,2}B_{2,1}\\
C_{1,2} = A_{1,1}B_{1,2} \,\,+ A_{1,2}B_{2,2}\\
C_{2,1} = A_{2,1}B_{1,1} \,\,+ A_{2,2}B_{2,1}\\
C_{2,2} = A_{2,1}B_{1,2} \,\,+ A_{2,2}B_{2,2}\\ $

Notamos de esta manera que existen 8 multiplicaciones que se efectuan para calcular la matriz $C_{i,j}$

Podemos aplicar la misma formula para matrices de tamaño N de la siguiente manera:

Sean A y B dos matrices cuadradas de tamaño $\, N\times N \,\,$ 

$ M_{1} , M_{2} , M_{3} , M_{4} \,\,$ submatrices de A de tamaño $\, \frac{N}{2} \times \frac{N}{2}$

$ P_{1} , P_{2} , P_{3} , P_{4} \,\,$ submatrices de B de tamaño $ \frac{N}{2} \times \frac{N}{2} $

La matriz C resultante de la multiplicación entre A y B está dada por:

$$ A = \begin{pmatrix} M_{1} & M_{2} \\ M_{3} & M_{4} \end{pmatrix} ,
\,\,B = \begin{pmatrix} P_{1} & P_{2} \\ P_{3} & P_{4} \end{pmatrix} , 
C = \begin{pmatrix} M_{1}P_{1}+M_{2}P_{3} & M_{1}P_{2}+M_{2}P_{4} \\ M_{3}P_{1}+M_{4}P_{3} & M_{3}P{2}+M_{4}P_{4} \end{pmatrix} $$

**_Recordar que dentro de las matrices A y B se trata de submatrices y por ende dentro de la matriz C son productos de matrices_**

Este método es también conocido como Dividir y Conquistar, el objetivo del algortimo de Strassen es reducir el tiempo de ejecución u orden de complejidad del algoritmo anterior.

## Algoritmo de Strassen

Vimos como en el método anterior las 8 multiplicaciones significan que en un eventual código tenemos 8 llamadas recursivas. 
La idea del método o algoritmo de Strassen es reducir el número de multiplicaciones y por ende llamadas recursivas dentro del código.
El algoritmo de Strassen es similar al método visto anteriormente en el sentido que también divide las matrices iniciales en submatrices de tamaño $\frac{N}{2} \times \frac{N}{2} $ cambiando la manera de calcular las submatrices.

Las fórmulas que se siguen para el cálculo de submatrices son (tomando las mismas submatrices anteriores):

$$ 
   K_{1} = M_{1}(P_{2}-P_{4})\\ \\
   K_{2} = P_{4}(M_{1}+M_{2})\\ \\
   K_{3} = P_{1}(M_{3}+M_{4})\\ \\
   K_{4} = M_{4}(P_{3}-P_{1})\\ \\
   K_{5} = (M_{1}+M_{4})(P_{1}+P_{4})\\ \\
   K_{6} = (M_{2}-M_{4})(P_{3}+P_{4})\\ \\
   K_{7} = (M_{1}-M_{3})(P_{1}+P_{2})\\ 
$$

De tal manera que la multiplicación de las matrices A y B resultando en C queda como:

$$
A \times B = \begin{pmatrix} M_{1} & M_{2} \\ M_{3} & M_{4} \end{pmatrix} \times \,\,\begin{pmatrix} P_{1} & P_{2} \\ P_{3} & P_{4} \end{pmatrix} = 
\begin{pmatrix} K_{5}+K_{4}-K_{2}+K_{6} & K_{1}+K_{2} \\ K_{3}+K_{4} & K_{1}+K_{5}-K_{3}-K_{7} \end{pmatrix} = C
$$

## Orden de complejidad 

El orden de complejidad de la fórmula general de la multlipicación de una matriz es de O($N^{3}$)

En el algoritmo de Dividir y Conquistar, mencionabamos que hacemos 8 multiplicaciones de dos matrices de tamaño $\frac{N}{2} \times \frac{N}{2} $ junto con 4 sumas.

El orden de complejidad puede entonces representarse como la suma de dos matrices junto con las multiplicaciones y tenemos gracias al teorema Maestro: 


_La suma de dos matrices puede considerarse de orden O($N^{2}$)_
$$
T(N) = 8 \times (\frac{N}{2}) + O(N^{2})\\
a = 8 \,,\,\, b = 2, \,\, \log_{b}(a) = \log_{2}(8) = 3 > 2\\
T(N) = O(N^{\log_{b}(a)} = O(N^{3})
$$

Mientras que el algoritmo de Strassen, hace 7 multiplicaciones, sumas y diferencias entre matrices. Con ayuda del teorema Maestro podemos expresar el orden de complejidad:
_La suma y diferencia entre matrices puede considerarse de orden O($N^{2}$)_
$$
T(N) = 7 \times (\frac{N}{2}) + O(N^{2})\\
a = 7 \,,\,\, b = 2, \,\, \log_{b}(a) = \log_{2}(7) \approx 2.8074 > 2\\
T(N) = O(N^{\log_{b}(a)} = O(N^{2.8})
$$


## Código en python del algoritmo

In [150]:
"""Importamos la librería numpy que nos dejará utilizar y operar con matrices"""
import numpy as np

In [153]:
"""
Definición de la función submatrix que divide 
una matriz en cuartos.
Recibe: matríz de tamaño NxN
Devuelve: tupla con 4 (n/2)x(n/2) submatrices correspondientes: a,b,c,d 
"""
def submatrix(matrix):
    row, col = matrix.shape
    rowN,colN = row//2,col//2
    return matrix[:rowN,:colN],matrix[:rowN, colN:], matrix[rowN:, :colN], matrix[rowN:, colN:] 

In [155]:
"""
Definición de la función principal de Strassen
Calcula el producto matricial mediante las fórmulas de los productos de Strassen, de forma recursiva.
Recibe: matriz NxN A and B
Devuelve: matriz C. El producto de A por B
"""
def strassen(A,B):
    #Caso base cuando el tamaño de la matriz sea 1x1 (multiplicación de dos números)
    if len(A) == 1:
        return A * B
        #Dividiendo las matrices en cuadrantes. Esto se hará de forma recursiva hasta llegar al caso base 
    a, b, c, d = submatrix(A)
    e, f, g, h = submatrix(B)

    #Calculando los 7 productos de Strassen
    p1 = strassen(a, f - h)
    p2 = strassen(a + b, h)
    p3 = strassen(c + d, e)
    p4 = strassen(d, g - e)
    p5 = strassen(a + d, e + h)
    p6 = strassen(b - d, g + h)
    p7 = strassen(a - c, e + f)

    #Calculando los valores de los 4 cuatrantes de la matriz final medinate las formulas
    c11 = p5 + p4 - p2 + p6
    c12 = p1 + p2
    c21 = p3 + p4
    c22 = p1 + p5 - p3 - p7

    #Dandole formato de matriz 
    c = np.vstack((np.hstack((c11, c12)), np.hstack((c21, c22))))

    return c

De esta manera tenemos el código de las funciones que utilizaremos para lograr la multiplicación de matrices por el método de Strassen:
probemos primero con dos matrices de $2 \times 2$ (utilizaremos una función que verifica que las matrices sean cuadradas y pares)

In [156]:
A = np.matrix([[1,5],[2,8]])
B = np.matrix([[3,6],[7,5]])
"""
Utilizamos la función de numpy shape para definir cuantas dimensiones y cuantos elementos tiene dentro de estas dimensiones la matriz 
"""
i,j = A.shape
k,l = B.shape

"""
Definición de una función que verifica el tamaño de ambas matrices y únicamente llama el método de Strassen si se trata de matrices cuadradas
Recibe: Dimensiones de las matrices A y B.
Devuelve: Matriz C resultante de la multiplicación por el método de Strassen o un mensaje de error.
"""
def squareParity(i,k):
    if(i%2==0 and k%2==0):
    #Condición que asegura que las matrices sean cuadradas y pares
        c = strassen(A, B)
    else:
        c ="Error. No se puede usar el método de strassen"

    return c

squareParity(i,k)

matrix([[38, 31],
        [62, 52]])

Con el código anterior obtenemos el resultado de la múltiplicación de $ A \times B = C $:


$$
A \times B = \begin{pmatrix} 1 & 5 \\ 2 & 8 \end{pmatrix} \times \begin{pmatrix} 3 & 6 \\ 7 & 5 \end{pmatrix} =  
\begin{pmatrix} 38 & 31 \\ 62 & 52 \end{pmatrix} = C
$$

El siguiente ejemplo muestra que el código de Strassen no funciona con matrices que no sean cuadradas o pares:

In [157]:
A = np.matrix([[1,2,3],[4,5,8],[7,6,16]])
B = np.matrix([[7,4,3],[10,9,16],[12,11,15]])

i,j = A.shape
k,l = B.shape

squareParity(i,k)

'Error. No se puede usar el método de strassen'

Con el siguiente ejemplo podemos comprobar que el código funciona con matrices pares:

In [158]:
A = np.matrix([[1,5,0,1,7,11,4,0],[2,8,3,2,12,14,4,8],[0,4,2,0,45,9,4,5],[1,2,1,0,0,1,2,0],[4,2,3,1,4,5,45,6],[21,4,56,3,7,9,2,4],[4,2,3,1,4,5,0,0],[21,4,56,3,7,9,11,12]])
B = np.matrix([[6,45,0,11,7,6,7,9],[2,32,30,2,16,15,4,6],[0,14,22,8,45,9,7,9],[1,10,11,1,22,0,6,7],[4,24,3,13,4,5,4,7],[21,4,56,36,8,9,6,7],[4,2,3,1,4,5,7,8],[21,4,56,3,7,9,12,11]])

i,j = A.shape
k,f = B.shape

squareParity(i,k)

matrix([[ 292,  435,  810,  513,  241,  235,  155,  204],
        [ 556,  792, 1608,  752,  553,  437,  335,  409],
        [ 498, 1300, 1095,  952,  457,  449,  352,  507],
        [  39,  131,  144,   61,  100,   64,   42,   53],
        [ 456,  526,  900,  368,  495,  425,  496,  571],
        [ 446, 2111, 2140, 1119, 2933,  852,  717,  910],
        [ 150,  412,  429,  305,  273,  146,  109,  145],
        [ 650, 2161, 2615, 1152, 3025,  969,  876, 1070]])

## Tiempo de ejecucion en computadora

La idea ahora es probar si efectivamente el método es más eficiente que el método regular de calcular multiplicación de matrices; tomamos entonces dos matrices:

$$
A = \begin{pmatrix} 2 & 3 & 4 & 5 \\ 0 & 6 & 9 & 1 \\ 10 & 9 & 11 & 16 \\ 1 & 0 & 23 & 17\end{pmatrix} ,
\,\,B = \begin{pmatrix} 21 & 13 & 4 & 7 \\ 1 & 3 & 6 & 11 \\ 10 & 4 & 3 & 15 \\ 11 & 0 & 13 & 18 \end{pmatrix}
$$

In [159]:
"""Código de multiplicación de matrices con el algoritmo con iteraciones anidadas en """
from timeit import default_timer as timer

X = [[2,3,4,5],[0,6,9,1],[10,9,11,16],[1,0,23,17]]
Y = [[21,13,4,7],[1,3,6,11],[10,4,3,15],[11,0,13,18]]
Z = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]
def multiply(X,Y,Z):
    for i in range(len(X)): 
        for j in range(len(Y[0])):
               for k in range(len(Y)):
                   Z[i][j] += X[i][k] * Y[k][j]
    return Z
start = timer()
multiply(X,Y,Z)
end = timer()
for r in Z:
    print(r)
print(end-start, "segundos")    

[140, 51, 103, 197]
[107, 54, 76, 219]
[505, 201, 335, 622]
[438, 105, 294, 658]
5.5500000598840415e-05 segundos


In [145]:
A = np.matrix([[2,3,4,5],[0,6,9,1],[10,9,11,16],[1,0,23,17]])
B = np.matrix([[21,13,4,7],[1,3,6,11],[10,4,3,15],[11,0,13,18]])

i,j = A.shape
k,f = B.shape

def squareParity(i,k):
    if(i%2==0 and k%2==0):
    #Condición que asegura que las matrices sean cuadradas y pares
        start = timer()
        c = strassen(A, B)
        end = timer()
        print(end-start,"segundos")
    else:
        c ="Error. No se puede usar el método de strassen"

    return c

squareParity(i,k)

0.0012332999976933934 segundos


matrix([[140,  51, 103, 197],
        [107,  54,  76, 219],
        [505, 201, 335, 622],
        [438, 105, 294, 658]])

Notamos como con una matriz pequeña no logramos consolidar que el algoritmo de Strassen tenga un menor tiempo de ejecución que el método regular de multiplicación de matrices asi que probemos con matrices de mayor orden.

In [160]:
X = [[1,5,0,1,7,11,4,0],[2,8,3,2,12,14,4,8],[0,4,2,0,45,9,4,5],[1,2,1,0,0,1,2,0],[4,2,3,1,4,5,45,6],[21,4,56,3,7,9,2,4],[4,2,3,1,4,5,0,0],[21,4,56,3,7,9,11,12]]
Y = [[6,45,0,11,7,6,7,9],[2,32,30,2,16,15,4,6],[0,14,22,8,45,9,7,9],[1,10,11,1,22,0,6,7],[4,24,3,13,4,5,4,7],[21,4,56,36,8,9,6,7],[4,2,3,1,4,5,7,8],[21,4,56,3,7,9,12,11]]
Z = [[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0]]
start = timer()
multiply(X,Y,Z)
end = timer()
for r in Z:
    print(r)
print(end-start, "segundos") 

[292, 435, 810, 513, 241, 235, 155, 204]
[556, 792, 1608, 752, 553, 437, 335, 409]
[498, 1300, 1095, 952, 457, 449, 352, 507]
[39, 131, 144, 61, 100, 64, 42, 53]
[456, 526, 900, 368, 495, 425, 496, 571]
[446, 2111, 2140, 1119, 2933, 852, 717, 910]
[150, 412, 429, 305, 273, 146, 109, 145]
[650, 2161, 2615, 1152, 3025, 969, 876, 1070]
0.0001506000044173561 segundos


In [161]:
A = np.matrix([[1,5,0,1,7,11,4,0],[2,8,3,2,12,14,4,8],[0,4,2,0,45,9,4,5],[1,2,1,0,0,1,2,0],[4,2,3,1,4,5,45,6],[21,4,56,3,7,9,2,4],[4,2,3,1,4,5,0,0],[21,4,56,3,7,9,11,12]])
B = np.matrix([[6,45,0,11,7,6,7,9],[2,32,30,2,16,15,4,6],[0,14,22,8,45,9,7,9],[1,10,11,1,22,0,6,7],[4,24,3,13,4,5,4,7],[21,4,56,36,8,9,6,7],[4,2,3,1,4,5,7,8],[21,4,56,3,7,9,12,11]])

def squareParity(i,k):
    if(i%2==0 and k%2==0):
    #Condición que asegura que las matrices sean cuadradas y pares
        start = timer()
        c = strassen(A, B)
        end = timer()
        print(end-start,"segundos")
    else:
        c ="Error. No se puede usar el método de strassen"

    return c

squareParity(i,k)

0.009631200002331752 segundos


matrix([[ 292,  435,  810,  513,  241,  235,  155,  204],
        [ 556,  792, 1608,  752,  553,  437,  335,  409],
        [ 498, 1300, 1095,  952,  457,  449,  352,  507],
        [  39,  131,  144,   61,  100,   64,   42,   53],
        [ 456,  526,  900,  368,  495,  425,  496,  571],
        [ 446, 2111, 2140, 1119, 2933,  852,  717,  910],
        [ 150,  412,  429,  305,  273,  146,  109,  145],
        [ 650, 2161, 2615, 1152, 3025,  969,  876, 1070]])

Utilizando matrices de orden $ 8 \times 8 $ vemos que tampoco hay una mejora en el tiempo de ejecución utilizando el algoritmo de Strassen.

## Conclusión

En conclusión, el algoritmo de Strassen mientras sea utilizado con matrices de orden "pequeño" no es una mejor alternativa que el método normal usando iteraciones.

Sin embargo algo que se puede notar al medir el tiempo de ejecución de cada algoritmo es que el orden en que crece el tiempo de ejecución de cada algoritmo es notable. 

Es decir, cuando pasamos de una matríz $ 4 \times 4 $ a una $ 8 \times 8 $ el tiempo de ejecución para el algoritmo iterativo pasa de un orden de $ 10^{-5} $ a un orden de $ 10^{-4} $ mientras que para el algoritmo de Strassen quedamos en un orden de $ 10^{-3} $.

Por tanto si seguimos subiendo de orden de matrices, podemos concluir que el algoritmo de Strassen tendrá un mejor tiempo de ejecución eventualmente como lo dicta el teorema Maestro. 